before_commands:
    - composer install
tools:
    php_cs_fixer:
        enabled: true
        extensions:
            - php
        command: php-cs-fixer
        filter:
            paths:
                - src/
        config:
            level: all
    php_sim:
        enabled: true
        min_mass: 30             # Defaults to 16
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
            include_standards:
                - vendor/bolt/codingstyle/PhpCodeSniffer/Bolt/
        filter:
            paths:
                - src/
#    external_code_coverage:
#        timeout: 1200
