before_commands:
    - composer install
tools:
    php_cs_fixer:
        extensions:
            - php
        command: php-cs-fixer
        enabled: true
        filter:
            paths:
                - src/
        config:
            level: all
    php_cpd:
        command: phpcpd
        min_lines:   5   # Minimum number of identical lines (default: 5)
        min_tokens: 70   # Minimum number of identical tokens (default: 70)
        names:           # A list of names that should be scanned (default: '*.php')
            - '*.php'
        excluded_dirs:   # A list of excluded directories.
            - vendor
            - files
            - app/cache/
        enabled: true
    php_code_sniffer:
        extensions:
            - php
        command: phpcs
        enabled: true
        filter:
            paths:
                - src/
        config:
            standard: PSR2
#    external_code_coverage:
#        timeout: 1200
