before_commands:
    - composer install
tools:
    php_cs_fixer:
        extensions:
            - php
        command: php-cs-fixer
        enabled: true
        filter:
            paths:
                - src/
        config:
            level: all
    php_sim:
        min_mass: 30             # Defaults to 16
        enabled: true
    php_code_sniffer:
        extensions:
            - php
        command: phpcs
        enabled: true
        filter:
            paths:
                - src/
        config:
            standard: PSR2
#    external_code_coverage:
#        timeout: 1200
