language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
matrix:
  allow_failures:
    - php: hhvm

script:
  - phpunit -c phpunit.xml.dist
  - ./run-functional-tests
  
before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-fr && sudo locale-gen fr_FR

before_script:
  - composer self-update || true
  - composer install --prefer-dist
  - mkdir -p tests/codeception/_log/
  - chmod 777 tests/codeception/_log/
  - mkdir -p tests/phpunit/Nut/resources/
  - chmod 777 tests/phpunit/Nut/resources/
  - mkdir -p app/cache
  - chmod 777 app/cache

after_script:
  - ./vendor/bin/ocular code-coverage:upload --format=php-clover coverage.xml
  
# cache vendor dirs
cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR

