language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

services:
  - mysql
  - postgresql

addons:
  postgresql: "9.3"

before_install:
  # Workaround for IPv6 problems connection to packagist.org
  - sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf"
  # Set up HHVM
  - |
    if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then
        echo 'xdebug.enable = On' >> /etc/hhvm/php.ini
        echo 'hhvm.jit = false' >> /etc/hhvm/php.ini
        sudo sh -c 'echo RUN_AS_USER=\"travis\"  >> /etc/default/hhvm'
        sudo sh -c 'echo RUN_AS_GROUP=\"travis\" >> /etc/default/hhvm'
        sudo service hhvm restart
        sleep 1
    fi
  # Start SMTP listener
  - sudo python -m smtpd -n -c DebuggingServer localhost:25 2>&1 > /dev/null &
  # Increase PHP memory limit. Required for Composer & PHPUnit.
  - echo "memory_limit=2G" ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
  # Set up Composer
  - composer self-update || true
  - composer global require hirak/prestissimo:~0.3
  - composer install --prefer-dist
  # Set up MySQL
  - mysql -e "CREATE DATABASE IF NOT EXISTS bolt_travis;" -u root
  - mysql -e "CREATE USER 'bolt_travis'@'localhost' IDENTIFIED BY 'bolt_travis';" -u root
  - mysql -e "GRANT ALL PRIVILEGES ON bolt_travis.* TO 'bolt_travis'@'localhost';" -u root
  - mysql -e "FLUSH PRIVILEGES;" -u root
  # Set up PostgreSQL
  - psql -c "CREATE DATABASE bolt_travis;" -U postgres || true
  - psql -c "CREATE USER bolt_travis WITH PASSWORD 'bolt_travis';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE bolt_travis TO bolt_travis;" -U postgres

script:
  ## Default install tests
  # PHPUnit
  - |
    export PHPUNIT_CMD="php -d memory_limit=2G ./vendor/bin/phpunit"
    if [[ $TRAVIS_EVENT_TYPE == "cron" && $TRAVIS_PHP_VERSION =~ ^7 ]] ; then
        composer require codeclimate/php-test-reporter:dev-master@dev
        $PHPUNIT_CMD --coverage-text --coverage-clover .coverage/clover/clover.xml --coverage-html .coverage/html/
        ./vendor/bin/test-reporter --coverage-report .coverage/clover/clover.xml
    else
        $PHPUNIT_CMD
    fi
  # Codeception set up (PHP >5.3)
  - ./vendor/codeception/codeception/codecept build
  # Codeception Sqlite run (PHP >5.3)
  - ./vendor/codeception/codeception/codecept run
  # Codeception MySQL run (PHP >5.3)
  - ./tests/travis/test-db-config mysql
  - ./vendor/codeception/codeception/codecept run
  # Codeception PostgreSQL run (PHP >5.3)
  - ./tests/travis/test-db-config postgres
  - ./vendor/codeception/codeception/codecept run

# Cache directories
cache:
  directories:
    - $COMPOSER_CACHE_DIR

