database:
  username: pilex
  password: pilex%1
  databasename: pilex

sitename: A sample Pilex site.
homepage: page/1
homepage_template: index.twig

debug: true
contentperpage: 4

# Date and Time formats
shortdate: j M ’ye
longdate: l j F Y
shorttime: H:i
longtime: H:i:s
fulldatetime: Y-m-d H:i:s