# Database setup. The driver can be either sqlite, mysql or postgres. For
# SQLite, only the databasename is required, while MySQL and PostgreSQL also
# require username, password and perhaps a hostname.
# If you're trying out Bolt, just keep it set to SQLite for now.
database:
  driver: sqlite
  databasename: bolt

# The name of the website
sitename: A sample Bolt site.

# The default content to use for the homepage, and the template to render it with.
homepage: page/1
homepage_template: index.twig

# The theme to use. Be sure to copy the theme/default folder, and change the
# name here accordingly. Don't edit the templates in theme/default, because
# they _will_ get updated in next releases
theme: default

# The default amount of records to show on overview pages. Can be overridden
# for each contenttype.
recordsperpage: 10

# The default template and amount of records to use for listing-pages on the site.
# Can be overridden for each contenttype.
listing_template: listing.twig
listing_records: 6

# The default template and amount of records to use for listing-pages on the site.
# Can be overridden for each contenttype, and for each record, if it has a
# 'templateselect' field.
record_template: record.twig

# Show the 'debug' nu in the lower right corner for logged-in user.
debug: true
developer_notices: false

# By default, the debugbar is only shown to logged-in users. Use the following
# option to show it to all users. You probably do not want to use this in a
# production environment
debug_show_loggedoff: false

# Use strict variables. This will make Bolt complain if you use {{ foo }},
# when foo doesn't exist.
strict_variables: false