database:
  driver: mysql
  username: bolt
  password: bolt%1
  databasename: bolt

sitename: A sample Bolt site.
homepage: page/1
homepage_template: index.twig
theme: default

debug: true
recordsperpage: 10

# Date and Time formats
shortdate: j M ’ye
longdate: l j F Y
shorttime: H:i
longtime: H:i:s
fulldatetime: Y-m-d H:i:s

strict_variables: false
