entries:
    name: Entries
    singular_name: Entry
    fields:
        title:
            type: text
            class: large
            default: Pompidom
        slug:
            type: slug
            uses: title
        image:
            type: image     
        imagetitle:
            type: text
        releasedate:
            type: date
            default: today
        dummydate:
            type: datetime
            default: now
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
    taxonomy: [ categories, tags ]
    template: entry.twig
    sort: datecreated DESC


pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large   
        slug:
            type: slug
            uses: title                    
        subtitle:
            label: Ondertitel
            type: text 
        template:
            type: templateselect 
            filter: '*.twig'   
        introduction:
            type: html
            height: 150px
        image:
            type: image            
        body:
            type: html
            height: 300px
    taxonomy: [ chapters ]
    template: page.twig
    sort: title
    contentperpage: 100
       

# possible field types:
# text - varchar(256) - input type text
# templateselect - varchar(256) - select with template filenames
# image - varchar(256) - image select/upload widget, stored as filename
# html - text (65kb) - wysiwyg element
# textarea - varchar(32768) - < textarea >
# datetime - datetime - date and time selector widget
# date - datetime - date selector widget