entries:
    name: Entries
    singular_name: Entry
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        image:
            type: image            
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
    taxonomy:
        type: categories, tags
    template: entry.twig


pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large   
        slug:
            type: slug
            uses: title                    
        subtitle:
            type: text 
        introduction:
            type: html
            height: 150px
        image:
            type: image            
        body:
            type: html
            height: 300px
        template:
            type: templateselect	
    taxonomy:
       type: chapters
    template: page.twig
       

# possible field types:
# text - varchar(256) - input type text
# templateselect - varchar(256) - select with template filenames
# image - varchar(256) - image select/upload widget, stored as filename
# html - text (65kb) - wysiwyg element
# textarea - varchar(32768) - <textarea>
# datetime - datetime - date and time selector widget
# date - datetime - date selector widget
