entries:
    name: Entries
    singular_name: Entry
    fields:
        title:
            type: text
        slug:
            type: slug
            uses: title
        teaser:
            type: html
        body:
            type: html
    taxonomy:
        type: categories, tags

pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
        subtitle:
            type: text            
        slug:
            type: slug
            uses: title
        teaser:
            type: html
        body:
            type: html
        template:
            type: templateselect	
    taxonomy:
       type: chapters
       

# possible field types:
# text - varchar(256) - input type text
# templateselect - varchar(256) - select with template filenames
# image - varchar(256) - image select/upload widget, stored as filename
# html - text (65kb) - wysiwyg element
# textarea - varchar(32768) - <textarea>
# datetime - datetime - date and time selector widget
# date - datetime - date selector widget
