agenda:
    name: Agenda
    singular_name: Event
    fields:
        title:
            type: text
            class: large
            default: Pompidom
        slug:
            type: slug
            uses: title
        datum:
            type: date
            default: today
        body:
            type: html
            height: 300px
    template: entry.twig
    sort: datecreated DESC
    contentperpage: 7


entries:
    name: Entries
    singular_name: Entry
    fields:
        title:
            type: text
            class: large
            default: Pompidom
        slug:
            type: slug
            uses: title
        image:
            type: image     
        releasedate:
            type: date
            default: today
        dummydate:
            type: datetime
            default: now
        divider2:
            type: divider
            label: "This is a divider"
        divider:
            type: divider
            line: true
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
    taxonomy: [ categories, tags ]
    template: entry.twig
    sort: datecreated DESC
    contentperpage: 7


pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large   
        slug:
            type: slug
            uses: title                    
        subtitle:
            label: Ondertitel
            type: text 
        image:
            type: image            
        introduction:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
        file:
            type: file-download
            label: File available for download     
        more:
            type: textarea
            height: 300px            
        template:
            type: templateselect 
            filter: \'*.twig\'   
    taxonomy: [ chapters ]
    template: page.twig
    sort: title
    contentperpage: 100
       

# possible field types:
# text - varchar(256) - input type text
# templateselect - varchar(256) - select with template filenames
# image - varchar(256) - image select/upload widget, stored as filename
# file - varchar(256) - image select/upload widget, stored as filename
# html - text (65kb) - wysiwyg element
# textarea - varchar(32768) - < textarea >
# datetime - datetime - date and time selector widget
# date - datetime - date selector widget
# divider - simple divider to enter a short text and/or line in the edit page.