tags:
    name: Tags
    slug: tags
    singular_slug: tag
    behaves_like: tags
    multiple: 1

categories:
    name: Categories
    slug: categories
    singular_slug: category
    behaves_like: categories
    multiple: 1
    options: [ news, events, movies, music, books ]

chapters:
    name: Chapters
    slug: chapters
    singular_slug: chapter
    behaves_like: grouping
    multiple: 0
