# This is the config file for the Simple Forms extension.

stylesheet: assets/simpleforms.css
template: assets/simpleforms_form.twig
mail_template: assets/simpleforms_mail.twig
message_ok: Thanks! Your message has been received.
message_error: There was an error in the form. Please check the form, and try again.
button_text: Send

contact:
  recipient_email: bob@twokings.nl
  recipient_name: Bob
  fields:
    subject:
      type: text
      class: wide
      label: Subject of your message
      placeholder: Just a quick message..
    name:
      type: text
      required: true
      placeholder: Your name..
    email:
      type: email
      label: Email address
      required: true
      placeholder: Your email..
    message:
      type: textarea
      required: true
      placeholder: Well, the other day I was thinking that maybe you ought to improve your website by adding ...
    option1:
      type: checkbox
      placeholder: Check me
      label: pompidom
      value: tralala
    option2:
      type: checkbox
      placeholder: Check me not
  button_text: Get in touch!


